[project]
name = "file-organizer"
version = "0.1.0"
description = ""
authors = [
    {name = "Marco",email = "marcoantonioporsch@live.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]

[tool.poetry]
packages = [{include = "file_organizer", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
